//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Product Category */
public struct Category: Codable, JSONEncodable, Hashable {

    /** Category Depth */
    public var depth: Int?
    public var id: String?
    /** Category Name */
    public var name: String?
    /** Parent ID */
    public var parentId: String?
    /** Category Slug */
    public var slug: String?

    public init(depth: Int? = nil, id: String? = nil, name: String? = nil, parentId: String? = nil, slug: String? = nil) {
        self.depth = depth
        self.id = id
        self.name = name
        self.parentId = parentId
        self.slug = slug
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case depth
        case id
        case name
        case parentId = "parent_id"
        case slug
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(depth, forKey: .depth)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encodeIfPresent(slug, forKey: .slug)
    }
}

