//
// Migration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The status object for the merchant payout account migration */
public struct Migration: Codable, JSONEncodable, Hashable {

    public enum Results: String, Codable, CaseIterable {
        case migrationRequired = "MIGRATION_REQUIRED"
        case migrationInProgress = "MIGRATION_IN_PROGRESS"
        case migrated = "MIGRATED"
        case notApplicable = "NOT_APPLICABLE"
        case error = "ERROR"
    }
    public enum Status: String, Codable, CaseIterable {
        case complete = "complete"
        case incomplete = "incomplete"
        case needsAttention = "needs_attention"
        case notApplicable = "not_applicable"
    }
    public var error: ModelError?
    /** The results of the merchant payout account migration check */
    public var results: Results?
    /** The status of the given property */
    public var status: Status?

    public init(error: ModelError? = nil, results: Results? = nil, status: Status? = nil) {
        self.error = error
        self.results = results
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case results
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(results, forKey: .results)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

