//
// OrderShippingMethodWrapperArray.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Array of Order Shipping Method Wrappers */
public struct OrderShippingMethodWrapperArray: Codable, JSONEncodable, Hashable {

    public var wrappers: [OrderShippingMethodWrapper]?

    public init(wrappers: [OrderShippingMethodWrapper]? = nil) {
        self.wrappers = wrappers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case wrappers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(wrappers, forKey: .wrappers)
    }
}

