//
// SyncStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The status object for the product sync */
public struct SyncStatus: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case complete = "COMPLETE"
        case incomplete = "INCOMPLETE"
        case needsAttention = "NEEDS_ATTENTION"
        case notApplicable = "NOT_APPLICABLE"
    }
    public var error: ModelError?
    public var results: ShopifyProductSyncs?
    /** The status of the given property */
    public var status: Status?

    public init(error: ModelError? = nil, results: ShopifyProductSyncs? = nil, status: Status? = nil) {
        self.error = error
        self.results = results
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case results
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(results, forKey: .results)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

