//
// OrderCustomer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The Customer Placing the Order */
public struct OrderCustomer: Codable, JSONEncodable, Hashable {

    /** ID of the User the Order Customer references */
    public var userId: Int64?
    /** First Name */
    public var firstName: String
    /** Last Name */
    public var lastName: String
    /** Email Address of Customer */
    public var email: String
    public var name: String?

    public init(userId: Int64? = nil, firstName: String, lastName: String, email: String, name: String? = nil) {
        self.userId = userId
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId = "user_id"
        case firstName = "first_name"
        case lastName = "last_name"
        case email
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

