//
// Variant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Variation Data */
public struct Variant: Codable, JSONEncodable, Hashable {

    /** ID of the Product Variant */
    public var productVariantId: String?
    /** ID of the Variant on the External Ecommerce Platform */
    public var externalId: String?
    /** Variant Name */
    public var name: String?
    /** Is the variant visual */
    public var visual: Bool? = false
    public var values: [VariantValue]?

    public init(productVariantId: String? = nil, externalId: String? = nil, name: String? = nil, visual: Bool? = false, values: [VariantValue]? = nil) {
        self.productVariantId = productVariantId
        self.externalId = externalId
        self.name = name
        self.visual = visual
        self.values = values
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productVariantId = "product_variant_id"
        case externalId = "external_id"
        case name
        case visual
        case values
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productVariantId, forKey: .productVariantId)
        try container.encodeIfPresent(externalId, forKey: .externalId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(visual, forKey: .visual)
        try container.encodeIfPresent(values, forKey: .values)
    }
}

