//
// BagFulfillmentSku.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BagFulfillmentSku: Codable, JSONEncodable, Hashable {

    /** ID of the fulfillment that contains this item. */
    public var fulfillmentId: Int64?
    public var id: Int64?
    /** ID of the SKU in the Bag. */
    public var orderSkuId: Int64?
    /** Quantity of the this item fulfilled by this fulfillment. */
    public var quantityFulfilled: Int?

    public init(fulfillmentId: Int64? = nil, id: Int64? = nil, orderSkuId: Int64? = nil, quantityFulfilled: Int? = nil) {
        self.fulfillmentId = fulfillmentId
        self.id = id
        self.orderSkuId = orderSkuId
        self.quantityFulfilled = quantityFulfilled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fulfillmentId = "fulfillment_id"
        case id
        case orderSkuId = "order_sku_id"
        case quantityFulfilled = "quantity_fulfilled"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fulfillmentId, forKey: .fulfillmentId)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(orderSkuId, forKey: .orderSkuId)
        try container.encodeIfPresent(quantityFulfilled, forKey: .quantityFulfilled)
    }
}

