//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Product Category */
public struct Category: Codable, JSONEncodable, Hashable {

    public var id: String?
    /** Category Name */
    public var name: String
    /** Category Slug */
    public var slug: String
    /** Parent ID */
    public var parentId: String?
    /** Category Depth */
    public var depth: Int

    public init(id: String? = nil, name: String, slug: String, parentId: String? = nil, depth: Int) {
        self.id = id
        self.name = name
        self.slug = slug
        self.parentId = parentId
        self.depth = depth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case slug
        case parentId = "parent_id"
        case depth
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encode(depth, forKey: .depth)
    }
}

