//
// OffersPublishedResults.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The results object for offers published */
public struct OffersPublishedResults: Codable, JSONEncodable, Hashable {

    /** The number of offers the merchant has published */
    public var count: Int?
    /** Boolean indicating if the merchant's product sync is complete, this status helps give context on why a merchant might not have any published offers */
    public var syncComplete: Bool?

    public init(count: Int? = nil, syncComplete: Bool? = nil) {
        self.count = count
        self.syncComplete = syncComplete
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case syncComplete = "sync_complete"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(syncComplete, forKey: .syncComplete)
    }
}

