//
// OrderPaymentMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payment Method belonging to an Order */
public struct OrderPaymentMethod: Codable, JSONEncodable, Hashable {

    /** Brand of Card */
    public var brand: String?
    /** Last Four Numbers on Card */
    public var lastFour: String?
    /** Card Expiration Month */
    public var expMonth: Int?
    /** Card Expiration Year */
    public var expYear: Int?
    /** Name as it appears on card. */
    public var cardholderName: String?
    /** ID of the referenced Payment Method */
    public var paymentMethodId: Int64
    /** Is Default Method */
    public var _default: Bool? = false

    public init(brand: String? = nil, lastFour: String? = nil, expMonth: Int? = nil, expYear: Int? = nil, cardholderName: String? = nil, paymentMethodId: Int64, _default: Bool? = false) {
        self.brand = brand
        self.lastFour = lastFour
        self.expMonth = expMonth
        self.expYear = expYear
        self.cardholderName = cardholderName
        self.paymentMethodId = paymentMethodId
        self._default = _default
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brand
        case lastFour = "last_four"
        case expMonth = "exp_month"
        case expYear = "exp_year"
        case cardholderName = "cardholder_name"
        case paymentMethodId = "payment_method_id"
        case _default = "default"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(brand, forKey: .brand)
        try container.encodeIfPresent(lastFour, forKey: .lastFour)
        try container.encodeIfPresent(expMonth, forKey: .expMonth)
        try container.encodeIfPresent(expYear, forKey: .expYear)
        try container.encodeIfPresent(cardholderName, forKey: .cardholderName)
        try container.encode(paymentMethodId, forKey: .paymentMethodId)
        try container.encodeIfPresent(_default, forKey: ._default)
    }
}

