//
// OrderTax.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Taxes belonging to an Order Bag */
public struct OrderTax: Codable, JSONEncodable, Hashable {

    /** ID of the Order the Tax belongs to */
    public var orderId: Int64
    /** ID of the Merchant the Bag belongs to */
    public var merchantId: Int
    /** SKUs covered by the Tax */
    public var skus: [String]?
    /** State abbreviation */
    public var state: String
    /** Postal/Zip Code */
    public var postalCode: String?
    /** Tax Rate */
    public var rate: Double
    /** Total Tax amount on Bag */
    public var amount: Int
    /** Description of the Tax */
    public var description: String?

    public init(orderId: Int64, merchantId: Int, skus: [String]? = nil, state: String, postalCode: String? = nil, rate: Double, amount: Int, description: String? = nil) {
        self.orderId = orderId
        self.merchantId = merchantId
        self.skus = skus
        self.state = state
        self.postalCode = postalCode
        self.rate = rate
        self.amount = amount
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderId = "order_id"
        case merchantId = "merchant_id"
        case skus
        case state
        case postalCode = "postal_code"
        case rate
        case amount
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orderId, forKey: .orderId)
        try container.encode(merchantId, forKey: .merchantId)
        try container.encodeIfPresent(skus, forKey: .skus)
        try container.encode(state, forKey: .state)
        try container.encodeIfPresent(postalCode, forKey: .postalCode)
        try container.encode(rate, forKey: .rate)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

