//
// SkuVariantValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Individual Variation Value for a Sku */
public struct SkuVariantValue: Codable, JSONEncodable, Hashable {

    /** Variant Value */
    public var value: String
    /** Variant Name */
    public var variant: String

    public init(value: String, variant: String) {
        self.value = value
        self.variant = variant
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case variant
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(variant, forKey: .variant)
    }
}

