//
// Sort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Sort: Codable, JSONEncodable, Hashable {

    public var unsorted: Bool?
    public var sorted: Bool?
    public var empty: Bool?

    public init(unsorted: Bool? = nil, sorted: Bool? = nil, empty: Bool? = nil) {
        self.unsorted = unsorted
        self.sorted = sorted
        self.empty = empty
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case unsorted
        case sorted
        case empty
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(unsorted, forKey: .unsorted)
        try container.encodeIfPresent(sorted, forKey: .sorted)
        try container.encodeIfPresent(empty, forKey: .empty)
    }
}

