//
// WebhookEventBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Webhook Event Body */
public struct WebhookEventBody: Codable, JSONEncodable, Hashable {

    public var body: [String: AnyCodable]?
    /** Date of creation */
    public var dateCreated: Date?
    public var length: Int?

    public init(body: [String: AnyCodable]? = nil, dateCreated: Date? = nil, length: Int? = nil) {
        self.body = body
        self.dateCreated = dateCreated
        self.length = length
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
        case dateCreated = "date_created"
        case length
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(dateCreated, forKey: .dateCreated)
        try container.encodeIfPresent(length, forKey: .length)
    }
}

