//
// Album.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Product Image Container */
public struct Album: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case offer = "OFFER"
        case sku = "SKU"
    }
    public var id: Int64?
    /** ID of the parent entity */
    public var parentId: Int64
    /** Parent Type */
    public var type: ModelType
    /** Name of Album */
    public var name: String?
    /** Album media */
    public var media: [Media]?

    public init(id: Int64? = nil, parentId: Int64, type: ModelType, name: String? = nil, media: [Media]? = nil) {
        self.id = id
        self.parentId = parentId
        self.type = type
        self.name = name
        self.media = media
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case parentId = "parent_id"
        case type
        case name
        case media
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(parentId, forKey: .parentId)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(media, forKey: .media)
    }
}

