//
// BagShippingMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Shipping Method applied to a Bag */
public struct BagShippingMethod: Codable, JSONEncodable, Hashable {

    public var bagId: Int64?
    public var shippingMethodId: String?

    public init(bagId: Int64? = nil, shippingMethodId: String? = nil) {
        self.bagId = bagId
        self.shippingMethodId = shippingMethodId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bagId = "bag_id"
        case shippingMethodId = "shipping_method_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bagId, forKey: .bagId)
        try container.encodeIfPresent(shippingMethodId, forKey: .shippingMethodId)
    }
}

