//
// CustomerAddress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Customer Address */
public struct CustomerAddress: Codable, JSONEncodable, Hashable {

    public var customer: OrderCustomer?
    public var shippingAddress: OrderAddress?
    public var billingAddress: OrderAddress?

    public init(customer: OrderCustomer? = nil, shippingAddress: OrderAddress? = nil, billingAddress: OrderAddress? = nil) {
        self.customer = customer
        self.shippingAddress = shippingAddress
        self.billingAddress = billingAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customer
        case shippingAddress = "shipping_address"
        case billingAddress = "billing_address"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customer, forKey: .customer)
        try container.encodeIfPresent(shippingAddress, forKey: .shippingAddress)
        try container.encodeIfPresent(billingAddress, forKey: .billingAddress)
    }
}

