//
// Meta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Additional Product Data */
public struct Meta: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    /** Offer Id */
    public var offerId: Int64
    /** Key */
    public var key: String
    /** Value */
    public var value: String

    public init(id: Int64? = nil, offerId: Int64, key: String, value: String) {
        self.id = id
        self.offerId = offerId
        self.key = key
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case offerId = "offer_id"
        case key
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(offerId, forKey: .offerId)
        try container.encode(key, forKey: .key)
        try container.encode(value, forKey: .value)
    }
}

