//
// SkuDimensions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Individual SkuDimensions */
public struct SkuDimensions: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case sku = "SKU"
        case shipping = "SHIPPING"
    }
    /** ID of SKU Dimensions Belong To */
    public var skuId: Int64?
    /** Weight of SKU */
    public var weight: Double?
    /** Height of SKU */
    public var height: Double?
    /** Width of SKU */
    public var width: Double?
    /** Length of SKU */
    public var length: Double?
    /** Dimensions Type */
    public var type: ModelType?

    public init(skuId: Int64? = nil, weight: Double? = nil, height: Double? = nil, width: Double? = nil, length: Double? = nil, type: ModelType? = nil) {
        self.skuId = skuId
        self.weight = weight
        self.height = height
        self.width = width
        self.length = length
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case skuId = "sku_id"
        case weight
        case height
        case width
        case length
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(skuId, forKey: .skuId)
        try container.encodeIfPresent(weight, forKey: .weight)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(length, forKey: .length)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

