//
// VariantValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Individual Variation Value */
public struct VariantValue: Codable, JSONEncodable, Hashable {

    /** ID of the Product Variation Value */
    public var productVariantValueId: String?
    /** ID of the Variant in the External Ecommerce Platform */
    public var externalId: String?
    /** Variant Value Name */
    public var name: String?
    /** ID's of SKU's containing this Variant Value */
    public var skuIds: [Int64]?

    public init(productVariantValueId: String? = nil, externalId: String? = nil, name: String? = nil, skuIds: [Int64]? = nil) {
        self.productVariantValueId = productVariantValueId
        self.externalId = externalId
        self.name = name
        self.skuIds = skuIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productVariantValueId = "product_variant_value_id"
        case externalId = "external_id"
        case name
        case skuIds = "sku_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productVariantValueId, forKey: .productVariantValueId)
        try container.encodeIfPresent(externalId, forKey: .externalId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(skuIds, forKey: .skuIds)
    }
}

