//
// WebhookError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Webhook Error */
public struct WebhookError: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    /** App ID */
    public var appId: Int64?
    /** ID of the webhook the error occurred on */
    public var webhookId: Int64?
    /** HTTP Status Code */
    public var statusCode: Int
    /** Response from the remote url */
    public var response: String?
    /** Date of webhook error creation */
    public var dateCreated: Date?
    /** Date of last webhook error update */
    public var dateLastModified: Date?

    public init(id: Int64? = nil, appId: Int64? = nil, webhookId: Int64? = nil, statusCode: Int, response: String? = nil, dateCreated: Date? = nil, dateLastModified: Date? = nil) {
        self.id = id
        self.appId = appId
        self.webhookId = webhookId
        self.statusCode = statusCode
        self.response = response
        self.dateCreated = dateCreated
        self.dateLastModified = dateLastModified
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case appId = "app_id"
        case webhookId = "webhook_id"
        case statusCode = "status_code"
        case response
        case dateCreated = "date_created"
        case dateLastModified = "date_last_modified"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(appId, forKey: .appId)
        try container.encodeIfPresent(webhookId, forKey: .webhookId)
        try container.encode(statusCode, forKey: .statusCode)
        try container.encodeIfPresent(response, forKey: .response)
        try container.encodeIfPresent(dateCreated, forKey: .dateCreated)
        try container.encodeIfPresent(dateLastModified, forKey: .dateLastModified)
    }
}

